"""BoneCloth MC2 OmniNode declarations.

骨骼布料解算器：把多条骨链当作布料粒子求解，支持按 root 列表顺序自动生成横向约束，
解决链骨只有纵向约束、相邻链互相穿插飘散的痛点。

与网格布料-MC2 共用同一套 solver kernel（distance/angle/bend/tether/collision/inertia/motion/post），
只替换 I/O：输入 armature + 根骨骼列表，输出写回 PoseBone.matrix_basis。

连接模式：
  0 = 仅纵向    只连父子骨，无横向
  1 = 顺序连接  按根骨列表顺序连接相邻链（默认，披肩/刘海/尾巴）
  2 = 顺序成环  同上但首末链成环（裙摆/围脖）
"""

import bpy
import mathutils

from .....PropertyCurve import float_curve_payload
from ...FunctionNodeCore import omni
from ...OmniNodeSocketMapping import _OmniBone, _OmniCache, _OmniFloatCurve
from .. import _Color
from ..physicsMC2.constants import MC2SystemConstants
from .runtime.controller import run_bone_cloth_mc2_node as _run_bone_cloth_mc2_node


def _mc2_curve_multiplier(value: float = 1.0, interpolation: str = "LINEAR", extend: str = "CLAMP") -> dict:
    value = float(value)
    return float_curve_payload(
        [
            {"x": 0.0, "y": value, "interpolation": interpolation},
            {"x": 1.0, "y": value, "interpolation": interpolation},
        ],
        value=1.0,
        interpolation=interpolation,
        extend=extend,
    )


@omni(
    enable=True,
    bl_label="骨骼布料-MC2",
    base_color=_Color.colorCat["Operator"],
    is_output_node=False,
    _INPUT_NAME=[
        "缓存",
        "骨架",
        "根骨骼",
        "连接模式",
        "旋转插值",
        "场景",
        "启用",
        "重置",
        "子步数",
        "迭代",
        "重力方向",
        "重力强度",
        "重力衰减",
        "重置后稳定时间",
        "混合权重",
        "阻尼",
        "阻尼曲线",
        "Tether启用",
        "Tether压缩",
        "距离启用",
        "距离刚度",
        "距离刚度曲线",
        "弯曲启用",
        "弯曲刚度",
        "弯曲刚度曲线",
        "角度恢复启用",
        "角度恢复",
        "角度恢复曲线",
        "角度恢复速度衰减",
        "角度恢复速度衰减曲线",
        "角度恢复重力衰减",
        "角度限制启用",
        "角度限制",
        "角度限制曲线",
        "角度限制刚度",
        "Anchor物体",
        "Anchor惯性",
        "World惯性",
        "World惯性平滑",
        "Local惯性",
        "深度惯性",
        "离心力",
        "World移动限速",
        "World旋转限速",
        "Local移动限速",
        "Local旋转限速",
        "粒子限速",
        "Teleport模式",
        "Teleport距离",
        "Teleport旋转",
        "动画姿态比例",
        "最大距离启用",
        "最大距离",
        "最大距离曲线",
        "碰撞半径",
        "Backstop启用",
        "Backstop半径",
        "Backstop距离",
        "Backstop距离曲线",
        "Motion刚度",
        "法线轴",
        "碰撞启用",
        "碰撞摩擦",
        "碰撞模式",
        "时间缩放",
        "跳过写回",
        "调试输出",
    ],
    input_init={
        "connection_mode": {
            "min_value": 0,
            "max_value": 2,
            "description": "0仅纵向，1顺序连接相邻链（默认），2顺序成环。按根骨列表顺序连接，不做距离查找。",
        },
        "rotational_interpolation": {
            "min_value": 0.0,
            "max_value": 1.0,
            "description": "骨骼旋转跟随程度：0保持初始朝向，1完全跟随模拟方向。",
        },
        "substeps": {"min_value": 1, "max_value": 16},
        "iterations": {"min_value": 0, "max_value": 64},
        "gravity_power": {"min_value": 0.0, "max_value": 100.0},
        "gravity_falloff": {"min_value": 0.0, "max_value": 1.0},
        "stablization_time_after_reset": {"min_value": 0.0, "max_value": 1.0},
        "blend_weight": {"min_value": 0.0, "max_value": 1.0},
        "damping": {"min_value": 0.0, "max_value": 1.0},
        "damping_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "tether_compression": {"min_value": 0.0, "max_value": 1.0},
        "distance_stiffness": {"min_value": 0.0, "max_value": 1.0},
        "distance_stiffness_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "bend_stiffness": {"min_value": 0.0, "max_value": 1.0},
        "bend_stiffness_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "angle_restoration_stiffness": {"min_value": 0.0, "max_value": 1.0},
        "angle_restoration_stiffness_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "angle_restoration_velocity_attenuation": {"min_value": 0.0, "max_value": 1.0},
        "angle_restoration_velocity_attenuation_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "angle_restoration_gravity_falloff": {"min_value": 0.0, "max_value": 1.0},
        "angle_limit": {"min_value": 0.0, "max_value": 180.0},
        "angle_limit_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "angle_limit_stiffness": {"min_value": 0.0, "max_value": 1.0},
        "anchor_inertia": {"min_value": 0.0, "max_value": 1.0},
        "world_inertia": {"min_value": 0.0, "max_value": 1.0},
        "movement_inertia_smoothing": {"min_value": 0.0, "max_value": 1.0},
        "local_inertia": {"min_value": 0.0, "max_value": 1.0},
        "depth_inertia": {"min_value": 0.0, "max_value": 1.0},
        "centrifugal": {"min_value": 0.0, "max_value": 1.0},
        "movement_speed_limit": {"min_value": -1.0, "max_value": 10.0},
        "rotation_speed_limit": {"min_value": -1.0, "max_value": 1440.0},
        "local_movement_speed_limit": {"min_value": -1.0, "max_value": 10.0},
        "local_rotation_speed_limit": {"min_value": -1.0, "max_value": 1440.0},
        "particle_speed_limit": {"min_value": -1.0, "max_value": 10.0},
        "teleport_mode": {"min_value": 0, "max_value": 2},
        "teleport_distance": {"min_value": 0.0},
        "teleport_rotation": {"min_value": 0.0},
        "animation_pose_ratio": {"min_value": 0.0, "max_value": 1.0},
        "max_distance": {"min_value": 0.0},
        "max_distance_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "backstop_radius": {"min_value": 0.0, "max_value": 10.0},
        "backstop_distance": {"min_value": 0.0},
        "backstop_distance_curve": {"default_value": _mc2_curve_multiplier(1.0)},
        "motion_stiffness": {"min_value": 0.0, "max_value": 1.0},
        "normal_axis": {"min_value": 0, "max_value": 5},
        "collision_radius": {"min_value": 0.0},
        "collider_friction": {"min_value": 0.0, "max_value": 0.5},
        "collider_collision_mode": {"min_value": 0, "max_value": 2},
        "time_scale": {"min_value": 0.0, "max_value": 1.0},
    },
    _OUTPUT_NAME=["缓存", "骨架", "骨骼数", "约束数"],
    omni_description="""
    MC2 风格骨骼布料 Python 参考解算器。

    输入一个骨架和多条骨链的根骨骼（多重输入）。每根骨骼 head 作为一个布料粒子，
    root 骨作为固定锚点。solver 与网格布料-MC2 同源，只替换骨骼 I/O。

    横向约束按“根骨骼”列表顺序连接相邻链，不做空间距离查找：用户填入列表的顺序
    就是布料面的横向走向。骨骼名一般带顺时针/逆时针序号，直接按序填入即可。

    结果写回 PoseBone.matrix_basis，只改骨骼旋转不改位置，兼容 connected 骨。
    """,
)
def boneClothMC2(
    cache_state: _OmniCache,
    armature_obj: bpy.types.Object,
    root_bones: list[_OmniBone] = None,
    connection_mode: int = 1,
    rotational_interpolation: float = 1.0,
    scene: bpy.types.Scene = None,
    enabled: bool = True,
    reset: bool = False,
    substeps: int = 1,
    iterations: int = 4,
    gravity_dir: mathutils.Vector = mathutils.Vector((0.0, 0.0, -1.0)),
    gravity_power: float = 9.8,
    gravity_falloff: float = 0.0,
    stablization_time_after_reset: float = 0.1,
    blend_weight: float = 1.0,
    damping: float = 0.2,
    damping_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_tether: bool = True,
    tether_compression: float = MC2SystemConstants.TETHER_COMPRESSION_LIMIT,
    use_distance: bool = True,
    distance_stiffness: float = 1.0,
    distance_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_bend: bool = True,
    bend_stiffness: float = 0.5,
    bend_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_angle_restoration: bool = True,
    angle_restoration_stiffness: float = 0.2,
    angle_restoration_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_restoration_velocity_attenuation: float = MC2SystemConstants.ANGLE_RESTORATION_VELOCITY_ATTENUATION,
    angle_restoration_velocity_attenuation_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_restoration_gravity_falloff: float = MC2SystemConstants.ANGLE_RESTORATION_GRAVITY_FALLOFF,
    use_angle_limit: bool = False,
    angle_limit: float = 0.0,
    angle_limit_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_limit_stiffness: float = 1.0,
    anchor_obj: bpy.types.Object = None,
    anchor_inertia: float = MC2SystemConstants.ANCHOR_INERTIA,
    world_inertia: float = MC2SystemConstants.WORLD_INERTIA,
    movement_inertia_smoothing: float = MC2SystemConstants.MOVEMENT_INERTIA_SMOOTHING,
    local_inertia: float = MC2SystemConstants.LOCAL_INERTIA,
    depth_inertia: float = MC2SystemConstants.DEPTH_INERTIA,
    centrifugal: float = MC2SystemConstants.CENTRIFUGAL_ACCELERATION,
    movement_speed_limit: float = MC2SystemConstants.MOVEMENT_SPEED_LIMIT,
    rotation_speed_limit: float = MC2SystemConstants.ROTATION_SPEED_LIMIT,
    local_movement_speed_limit: float = MC2SystemConstants.LOCAL_MOVEMENT_SPEED_LIMIT,
    local_rotation_speed_limit: float = MC2SystemConstants.LOCAL_ROTATION_SPEED_LIMIT,
    particle_speed_limit: float = MC2SystemConstants.PARTICLE_SPEED_LIMIT,
    teleport_mode: int = 0,
    teleport_distance: float = MC2SystemConstants.TELEPORT_DISTANCE,
    teleport_rotation: float = MC2SystemConstants.TELEPORT_ROTATION,
    animation_pose_ratio: float = 0.0,
    use_max_distance: bool = False,
    max_distance: float = 0.0,
    max_distance_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    collision_radius: float = 0.0,
    use_backstop: bool = False,
    backstop_radius: float = 0.0,
    backstop_distance: float = 0.0,
    backstop_distance_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    motion_stiffness: float = 1.0,
    normal_axis: int = 1,
    use_collider_collision: bool = True,
    collider_friction: float = 0.05,
    collider_collision_mode: int = 1,
    time_scale: float = 1.0,
    skip_writing: bool = False,
    debug_output: bool = False,
) -> tuple[_OmniCache, bpy.types.Object, int, int]:
    return _run_bone_cloth_mc2_node(
        cache_state,
        armature_obj,
        root_bones,
        connection_mode,
        rotational_interpolation,
        scene,
        enabled,
        reset,
        substeps,
        iterations,
        gravity_dir,
        gravity_power,
        gravity_falloff,
        stablization_time_after_reset,
        blend_weight,
        damping,
        damping_curve,
        use_tether,
        tether_compression,
        use_distance,
        distance_stiffness,
        distance_stiffness_curve,
        use_bend,
        bend_stiffness,
        bend_stiffness_curve,
        use_angle_restoration,
        angle_restoration_stiffness,
        angle_restoration_stiffness_curve,
        angle_restoration_velocity_attenuation,
        angle_restoration_velocity_attenuation_curve,
        angle_restoration_gravity_falloff,
        use_angle_limit,
        angle_limit,
        angle_limit_curve,
        angle_limit_stiffness,
        anchor_obj,
        anchor_inertia,
        world_inertia,
        movement_inertia_smoothing,
        local_inertia,
        depth_inertia,
        centrifugal,
        movement_speed_limit,
        rotation_speed_limit,
        local_movement_speed_limit,
        local_rotation_speed_limit,
        particle_speed_limit,
        teleport_mode,
        teleport_distance,
        teleport_rotation,
        animation_pose_ratio,
        use_max_distance,
        max_distance,
        max_distance_curve,
        collision_radius,
        use_backstop,
        backstop_radius,
        backstop_distance,
        backstop_distance_curve,
        motion_stiffness,
        normal_axis,
        use_collider_collision,
        collider_friction,
        collider_collision_mode,
        time_scale,
        skip_writing,
        debug_output,
    )


_BONE_CLOTH_MC2_CPP_META = dict(boneClothMC2.__meta)
_BONE_CLOTH_MC2_CPP_META["bl_label"] = "骨骼布料-MC2-CPP"
_BONE_CLOTH_MC2_CPP_META["omni_description"] = """
    骨骼布料-MC2 的 C++ 后端版本。

    与骨骼布料-MC2 共用骨链采集、拓扑构建、cache、BasePose 同步、inertia 准备和骨骼旋转写回，
    但把每帧核心求解循环交给 hotools_native.solve_meshcloth_mc2。
    节点输入输出与 Python 版完全一致，可随时切换对比效果和性能。
    """


@omni(**_BONE_CLOTH_MC2_CPP_META)
def boneClothMC2Cpp(
    cache_state: _OmniCache,
    armature_obj: bpy.types.Object,
    root_bones: list[_OmniBone] = None,
    connection_mode: int = 1,
    rotational_interpolation: float = 1.0,
    scene: bpy.types.Scene = None,
    enabled: bool = True,
    reset: bool = False,
    substeps: int = 1,
    iterations: int = 4,
    gravity_dir: mathutils.Vector = mathutils.Vector((0.0, 0.0, -1.0)),
    gravity_power: float = 9.8,
    gravity_falloff: float = 0.0,
    stablization_time_after_reset: float = 0.1,
    blend_weight: float = 1.0,
    damping: float = 0.2,
    damping_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_tether: bool = True,
    tether_compression: float = MC2SystemConstants.TETHER_COMPRESSION_LIMIT,
    use_distance: bool = True,
    distance_stiffness: float = 1.0,
    distance_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_bend: bool = True,
    bend_stiffness: float = 0.5,
    bend_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    use_angle_restoration: bool = True,
    angle_restoration_stiffness: float = 0.2,
    angle_restoration_stiffness_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_restoration_velocity_attenuation: float = MC2SystemConstants.ANGLE_RESTORATION_VELOCITY_ATTENUATION,
    angle_restoration_velocity_attenuation_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_restoration_gravity_falloff: float = MC2SystemConstants.ANGLE_RESTORATION_GRAVITY_FALLOFF,
    use_angle_limit: bool = False,
    angle_limit: float = 0.0,
    angle_limit_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    angle_limit_stiffness: float = 1.0,
    anchor_obj: bpy.types.Object = None,
    anchor_inertia: float = MC2SystemConstants.ANCHOR_INERTIA,
    world_inertia: float = MC2SystemConstants.WORLD_INERTIA,
    movement_inertia_smoothing: float = MC2SystemConstants.MOVEMENT_INERTIA_SMOOTHING,
    local_inertia: float = MC2SystemConstants.LOCAL_INERTIA,
    depth_inertia: float = MC2SystemConstants.DEPTH_INERTIA,
    centrifugal: float = MC2SystemConstants.CENTRIFUGAL_ACCELERATION,
    movement_speed_limit: float = MC2SystemConstants.MOVEMENT_SPEED_LIMIT,
    rotation_speed_limit: float = MC2SystemConstants.ROTATION_SPEED_LIMIT,
    local_movement_speed_limit: float = MC2SystemConstants.LOCAL_MOVEMENT_SPEED_LIMIT,
    local_rotation_speed_limit: float = MC2SystemConstants.LOCAL_ROTATION_SPEED_LIMIT,
    particle_speed_limit: float = MC2SystemConstants.PARTICLE_SPEED_LIMIT,
    teleport_mode: int = 0,
    teleport_distance: float = MC2SystemConstants.TELEPORT_DISTANCE,
    teleport_rotation: float = MC2SystemConstants.TELEPORT_ROTATION,
    animation_pose_ratio: float = 0.0,
    use_max_distance: bool = False,
    max_distance: float = 0.0,
    max_distance_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    collision_radius: float = 0.0,
    use_backstop: bool = False,
    backstop_radius: float = 0.0,
    backstop_distance: float = 0.0,
    backstop_distance_curve: _OmniFloatCurve = _mc2_curve_multiplier(1.0),
    motion_stiffness: float = 1.0,
    normal_axis: int = 1,
    use_collider_collision: bool = True,
    collider_friction: float = 0.05,
    collider_collision_mode: int = 1,
    time_scale: float = 1.0,
    skip_writing: bool = False,
    debug_output: bool = False,
) -> tuple[_OmniCache, bpy.types.Object, int, int]:
    return _run_bone_cloth_mc2_node(
        cache_state,
        armature_obj,
        root_bones,
        connection_mode,
        rotational_interpolation,
        scene,
        enabled,
        reset,
        substeps,
        iterations,
        gravity_dir,
        gravity_power,
        gravity_falloff,
        stablization_time_after_reset,
        blend_weight,
        damping,
        damping_curve,
        use_tether,
        tether_compression,
        use_distance,
        distance_stiffness,
        distance_stiffness_curve,
        use_bend,
        bend_stiffness,
        bend_stiffness_curve,
        use_angle_restoration,
        angle_restoration_stiffness,
        angle_restoration_stiffness_curve,
        angle_restoration_velocity_attenuation,
        angle_restoration_velocity_attenuation_curve,
        angle_restoration_gravity_falloff,
        use_angle_limit,
        angle_limit,
        angle_limit_curve,
        angle_limit_stiffness,
        anchor_obj,
        anchor_inertia,
        world_inertia,
        movement_inertia_smoothing,
        local_inertia,
        depth_inertia,
        centrifugal,
        movement_speed_limit,
        rotation_speed_limit,
        local_movement_speed_limit,
        local_rotation_speed_limit,
        particle_speed_limit,
        teleport_mode,
        teleport_distance,
        teleport_rotation,
        animation_pose_ratio,
        use_max_distance,
        max_distance,
        max_distance_curve,
        collision_radius,
        use_backstop,
        backstop_radius,
        backstop_distance,
        backstop_distance_curve,
        motion_stiffness,
        normal_axis,
        use_collider_collision,
        collider_friction,
        collider_collision_mode,
        time_scale,
        skip_writing,
        debug_output,
        solver_backend="cpp",
    )
