#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace hotools::mc2_internal {

struct Vec3 {
    float x = 0.0f;
    float y = 0.0f;
    float z = 0.0f;
};

// Every translation unit that accesses this layout includes this header directly.
struct Mc2ContextV0 {
    std::int64_t vertex_count = 0;
    std::int32_t setup_kind = 0;
    std::int64_t parameter_revision = 0;
    std::int64_t proxy_static_revision = 0;
    std::int64_t baseline_static_revision = 0;
    std::int64_t bone_static_revision = 0;
    std::int64_t distance_static_revision = 0;
    std::int64_t bending_static_revision = 0;
    std::int64_t center_static_revision = 0;
    std::int64_t self_collision_static_revision = 0;
    std::int64_t owned_static_take_count = 0;
    std::int64_t static_clone_count = 0;
    std::int64_t center_static_rebuild_count = 0;
    std::int64_t dynamic_revision = 0;
    std::int64_t collider_revision = 0;
    std::int64_t reset_count = 0;
    std::int64_t step_count = 0;
    std::int64_t distance_solve_count = 0;
    std::int64_t particle_prediction_count = 0;
    std::int64_t particle_inertia_count = 0;
    std::int64_t bending_solve_count = 0;
    std::int64_t tether_solve_count = 0;
    std::int64_t angle_solve_count = 0;
    std::int64_t motion_solve_count = 0;
    std::int64_t point_collision_solve_count = 0;
    std::int64_t edge_collision_solve_count = 0;
    std::int64_t self_primitive_update_count = 0;
    std::int64_t self_grid_update_count = 0;
    std::int64_t self_candidate_update_count = 0;
    std::int64_t self_contact_build_count = 0;
    std::int64_t self_contact_update_count = 0;
    std::int64_t self_contact_solver_iteration_count = 0;
    std::int64_t self_contact_sum_count = 0;
    std::int64_t self_intersect_detection_count = 0;
    std::int64_t self_intersect_solve_count = 0;
    std::int64_t center_dynamic_revision = 0;
    std::int64_t step_interpolation_revision = 0;
    std::int64_t center_step_count = 0;
    std::int64_t center_frame_shift_count = 0;
    std::int64_t center_negative_scale_teleport_count = 0;
    std::int64_t particle_teleport_evaluation_revision = -1;
    std::int64_t particle_teleport_apply_count = 0;
    std::int64_t particle_teleport_trigger_count = 0;
    std::int32_t particle_teleport_mode = 0;
    std::int64_t team_options_revision = 0;
    std::int64_t static_fingerprint_revision = 0;
    std::int64_t baseline_pose_rebuild_count = 0;
    std::int64_t bone_line_output_count = 0;
    std::int64_t bone_triangle_output_count = 0;
    std::int64_t frame = 0;
    std::int64_t generation = 0;
    float velocity_weight = 1.0f;
    float gravity_ratio = 1.0f;
    float scale_ratio = 1.0f;
    float negative_scale_sign = 1.0f;
    float frame_interpolation = 1.0f;
    float animation_pose_ratio = 0.0f;
    float particle_teleport_max_distance = 0.0f;
    float particle_teleport_max_rotation_degrees = 0.0f;
    float particle_teleport_distance_threshold = 0.0f;
    float particle_teleport_rotation_threshold_degrees = 0.0f;
    bool parameters_ready = false;
    bool proxy_static_ready = false;
    bool baseline_static_ready = false;
    bool bone_static_ready = false;
    bool distance_static_ready = false;
    bool bending_static_ready = false;
    bool self_collision_static_ready = false;
    bool self_primitive_dynamic_ready = false;
    bool self_grid_dynamic_ready = false;
    bool self_candidate_ready = false;
    bool self_contact_ready = false;
    bool self_intersect_detection_ready = false;
    bool self_intersect_flags_ready = false;
    bool tether_enabled = false;
    bool center_static_ready = false;
    bool center_dynamic_ready = false;
    bool center_frame_ready = false;
    bool center_result_ready = false;
    bool dynamic_ready = false;
    bool component_pose_ready = false;
    bool particle_teleport_threshold_debug_ready = false;
    bool particle_teleport_status_debug_ready = false;
    bool initialized = false;
    bool static_fingerprint_ready = false;
    bool released = false;
    std::string static_topology_fingerprint;
    std::string static_geometry_fingerprint;
    std::string static_surface_fingerprint;
    std::string static_config_fingerprint;
    std::string static_overall_fingerprint;
    std::vector<float> float_values;
    std::vector<std::int32_t> int_values;
    std::vector<float> curve_values;
    std::vector<float> dynamic_positions;
    std::vector<float> dynamic_rotations;
    std::vector<float> old_dynamic_positions;
    std::vector<float> old_dynamic_rotations;
    std::array<float, 3> old_component_position {};
    std::array<float, 4> old_component_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> old_component_scale {1.0f, 1.0f, 1.0f};
    std::array<float, 3> component_position {};
    std::array<float, 4> component_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> component_scale {1.0f, 1.0f, 1.0f};
    std::array<float, 3> component_reference_position {};
    std::array<float, 4> component_reference_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> component_reference_scale {1.0f, 1.0f, 1.0f};
    std::vector<float> particle_teleport_debug_old_positions;
    std::vector<float> particle_teleport_debug_positions;
    std::vector<float> particle_teleport_debug_old_rotations;
    std::vector<float> particle_teleport_debug_rotations;
    std::vector<std::uint8_t> particle_teleport_debug_eligible;
    std::vector<float> particle_teleport_debug_status_positions;
    std::vector<std::uint8_t> particle_teleport_debug_status;
    std::vector<float> state_positions;
    std::vector<float> state_rotations;
    std::vector<float> state_velocities;
    std::vector<float> velocity_reference_positions;
    std::vector<float> particle_friction;
    std::vector<float> particle_static_friction;
    std::vector<float> particle_collision_normals;
    std::vector<float> particle_real_velocities;
    std::vector<float> animated_base_positions;
    std::vector<float> animated_base_rotations;
    std::vector<float> step_basic_positions;
    std::vector<float> step_basic_rotations;
    std::vector<float> proxy_local_positions;
    std::vector<float> proxy_local_normals;
    std::vector<float> proxy_local_tangents;
    std::vector<float> proxy_uvs;
    std::vector<float> frame_triangle_uvs;
    std::vector<std::uint8_t> proxy_attributes;
    std::vector<float> proxy_radius_multipliers;
    std::vector<std::int32_t> proxy_edges;
    std::vector<std::int32_t> proxy_triangles;
    std::vector<std::int32_t> baseline_parents;
    std::vector<std::int32_t> baseline_child_ranges;
    std::vector<std::int32_t> baseline_child_data;
    std::vector<std::uint8_t> baseline_flags;
    std::vector<std::int32_t> baseline_ranges;
    std::vector<std::int32_t> baseline_data;
    std::vector<std::int32_t> baseline_roots;
    std::vector<float> baseline_depths;
    std::vector<float> baseline_local_positions;
    std::vector<float> baseline_local_rotations;
    std::vector<std::int32_t> bone_vertex_to_vertex_ranges;
    std::vector<std::int32_t> bone_vertex_to_vertex_data;
    std::vector<std::int32_t> bone_vertex_to_triangle_ranges;
    std::vector<std::int32_t> bone_vertex_to_triangle_data;
    std::vector<float> bone_vertex_bind_pose_positions;
    std::vector<float> bone_vertex_bind_pose_rotations;
    std::vector<float> bone_normal_adjustment_rotations;
    std::vector<float> bone_vertex_to_transform_rotations;
    std::vector<float> bone_output_positions;
    std::vector<float> bone_output_rotations;
    std::vector<std::int32_t> distance_ranges;
    std::vector<std::int32_t> distance_targets;
    std::vector<float> distance_rest_signed;
    std::vector<std::int32_t> bending_quads;
    std::vector<float> bending_rest_angle_or_volume;
    std::vector<std::int8_t> bending_sign_or_volume;
    std::vector<std::uint32_t> self_primitive_flags;
    std::vector<std::int32_t> self_particle_indices;
    std::vector<float> self_primitive_depths;
    std::vector<std::uint64_t> self_topology_neighbor_keys;
    std::vector<float> self_primitive_inverse_masses;
    std::vector<float> self_primitive_aabb_min;
    std::vector<float> self_primitive_aabb_max;
    std::vector<float> self_primitive_thickness;
    std::vector<std::int32_t> self_primitive_owner_indices;
    std::vector<std::int32_t> self_owner_primary_group_bits;
    std::vector<std::int32_t> self_owner_collided_by_groups;
    std::vector<std::int32_t> self_primitive_grids;
    std::vector<std::int32_t> self_grid_hashes;
    std::vector<std::int32_t> self_grid_starts;
    std::vector<std::int32_t> self_grid_counts;
    std::vector<std::int32_t> self_contact_candidates;
    std::vector<std::int32_t> self_contact_primitive_indices;
    std::vector<std::int32_t> self_contact_types;
    std::vector<std::uint8_t> self_contact_enabled;
    std::vector<float> self_contact_thickness;
    std::vector<float> self_contact_s;
    std::vector<float> self_contact_t;
    std::vector<float> self_contact_normals;
    std::int64_t self_point_primitive_count = 0;
    std::int64_t self_edge_primitive_count = 0;
    std::int64_t self_triangle_primitive_count = 0;
    std::int64_t self_point_grid_count = 0;
    std::int64_t self_edge_grid_count = 0;
    std::int64_t self_triangle_grid_count = 0;
    std::int64_t self_primitive_frame = 0;
    std::int64_t self_primitive_generation = 0;
    float self_max_primitive_size = 0.0f;
    float self_grid_size = 0.0f;
    std::vector<std::uint64_t> self_contact_keys;
    std::vector<std::int32_t> self_intersect_records;
    std::vector<std::uint8_t> self_particle_intersect_flags;
    std::int64_t self_intersect_detection_frame = 0;
    std::int64_t self_intersect_detection_generation = 0;
    std::int32_t collided_by_groups = 0;
    std::vector<std::int32_t> collider_types;
    std::vector<std::int32_t> collider_group_bits;
    std::vector<float> collider_centers;
    std::vector<float> collider_segment_a;
    std::vector<float> collider_segment_b;
    std::vector<float> collider_old_centers;
    std::vector<float> collider_old_segment_a;
    std::vector<float> collider_old_segment_b;
    std::vector<float> collider_radii;
    std::vector<std::int32_t> center_fixed_indices;
    std::vector<float> center_local_position;
    std::vector<float> center_initial_local_gravity_direction;
    std::array<float, 3> center_old_frame_world_position {};
    std::array<float, 3> center_frame_world_position {};
    std::array<float, 4> center_old_frame_world_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 4> center_frame_world_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> center_old_frame_world_scale {1.0f, 1.0f, 1.0f};
    std::array<float, 3> center_frame_world_scale {1.0f, 1.0f, 1.0f};
    std::array<float, 3> center_old_world_position {};
    std::array<float, 4> center_old_world_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> center_initial_scale {1.0f, 1.0f, 1.0f};
    std::array<float, 3> center_negative_scale_direction {1.0f, 1.0f, 1.0f};
    float center_distance_weight = 1.0f;
    std::array<float, 3> center_now_world_position {};
    std::array<float, 4> center_now_world_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> center_step_vector {};
    std::array<float, 4> center_step_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> center_inertia_vector {};
    std::array<float, 4> center_inertia_rotation {0.0f, 0.0f, 0.0f, 1.0f};
    std::array<float, 3> center_rotation_axis {};
    float center_step_move_inertia_ratio = 1.0f;
    float center_step_rotation_inertia_ratio = 1.0f;
    float center_angular_velocity = 0.0f;
    float center_gravity_dot = 1.0f;
    float center_blend_weight = 1.0f;
};

struct Mc2InteractionParticipantV0 {
    Mc2ContextV0* context = nullptr;
    std::int32_t primary_group_bit = 0;
    std::int32_t collided_by_groups = 0;
    std::size_t vertex_offset = 0;
    std::size_t step_index = 0;
};

struct Mc2InteractionV0 {
    Mc2ContextV0 aggregate;
    std::vector<Mc2InteractionParticipantV0> participants;
    std::vector<std::uintptr_t> scope_identity;
    std::vector<float> old_positions;
    std::int64_t scope_revision = 0;
    std::int64_t invalidation_count = 0;
    std::int64_t step_count = 0;
    std::int64_t pair_count = 0;
    std::int64_t candidate_count = 0;
    std::int64_t contact_count = 0;
    std::int64_t intersect_record_count = 0;
    bool released = false;
};

struct Mc2ContextStepStateV0 {
    Mc2ContextV0* context = nullptr;
    std::vector<float> previous_positions;
    bool center_step_active = false;
};

}  // namespace hotools::mc2_internal
