"""MC2 Python 后端的常量与 cache schema 标识。"""

MC2_CACHE_KIND = "MESH_PHYSICS_MC2"
MC2_SOLVER_VERSION = 12

MC2_ATTR_INVALID = 1 << 0
MC2_ATTR_FIXED = 1 << 1
MC2_ATTR_MOVE = 1 << 2
MC2_ATTR_MOTION = 1 << 3

MC2_DISTANCE_TYPE_VERTICAL = 1
MC2_DISTANCE_TYPE_HORIZONTAL = 2
MC2_DISTANCE_TYPE_STRUCTURAL = MC2_DISTANCE_TYPE_VERTICAL
MC2_DISTANCE_TYPE_BEND_DISTANCE_APPROX = 16
MC2_BEND_KIND_DISTANCE_APPROX = "distance_approx"
MC2_BEND_KIND_DIRECTION_DIHEDRAL = "direction_dihedral"

MC2_CURVE_READY_PARAMETERS = {
    "distance_stiffness",
    "bend_stiffness",
    "radius",
    "max_distance",
    "tether_compression",
    "tether_stretch",
    "motion_stiffness",
    "backstop_radius",
    "backstop_distance",
    "collider_friction",
    "angle_restoration_stiffness",
    "angle_limit",
    "angle_limit_stiffness",
    "world_inertia",
    "movement_inertia_smoothing",
    "local_inertia",
    "depth_inertia",
    "centrifugal",
    "movement_speed_limit",
    "rotation_speed_limit",
    "local_movement_speed_limit",
    "local_rotation_speed_limit",
    "particle_speed_limit",
    "damping",
}


class MC2SystemConstants:
    """与 MC2 Define.System 对齐的求解常量。"""

    EPSILON = 0.00000001
    MAX_DISTANCE_RATIO_FUTURE_PREDICTION = 1.3
    FRICTION_MASS = 3.0
    DEPTH_MASS = 5.0
    TETHER_COMPRESSION_LIMIT = 0.4
    TETHER_STRETCH_LIMIT = 0.03
    TETHER_STIFFNESS_WIDTH = 0.3
    TETHER_COMPRESSION_STIFFNESS = 1.0
    TETHER_STRETCH_STIFFNESS = 1.0
    TETHER_COMPRESSION_VELOCITY_ATTENUATION = 0.7
    TETHER_STRETCH_VELOCITY_ATTENUATION = 0.7
    DISTANCE_VELOCITY_ATTENUATION = 0.3
    DISTANCE_HORIZONTAL_STIFFNESS = 0.5
    DISTANCE_FIXED_INVERSE_MASS = 1.0 / 50.0
    TRIANGLE_BENDING_MAX_ANGLE = 120.0
    TRIANGLE_BENDING_FIXED_INVERSE_MASS = 0.01
    TRIANGLE_VOLUME_MIN_ANGLE = 90.0
    TRIANGLE_VOLUME_MAX_ANGLE = 179.0
    TRIANGLE_VOLUME_SCALE = 1000.0
    ANGLE_LIMIT_ITERATION = 3
    ANGLE_LIMIT_ATTENUATION = 0.9
    ANGLE_RESTORATION_SCALE = 0.2
    ANGLE_RESTORATION_VELOCITY_ATTENUATION = 0.8
    ANGLE_RESTORATION_GRAVITY_FALLOFF = 0.0
    ANGLE_LIMIT_STIFFNESS = 1.0
    WORLD_INERTIA = 1.0
    MOVEMENT_INERTIA_SMOOTHING = 0.4
    LOCAL_INERTIA = 1.0
    DEPTH_INERTIA = 0.0
    CENTRIFUGAL_ACCELERATION = 0.0
    MOVEMENT_SPEED_LIMIT = 5.0
    ROTATION_SPEED_LIMIT = 720.0
    LOCAL_MOVEMENT_SPEED_LIMIT = -1.0
    LOCAL_ROTATION_SPEED_LIMIT = -1.0
    TELEPORT_DISTANCE = 0.5
    TELEPORT_ROTATION = 90.0
    MOTION_VELOCITY_ATTENUATION = 0.95
    FRICTION_DAMPING_RATE = 0.6
    STATIC_FRICTION_INCREASE = 0.04
    STATIC_FRICTION_DECAY = 0.05
    STATIC_FRICTION_VELOCITY_WIDTH = 0.2
    PARTICLE_SPEED_LIMIT = 4.0
    COLLIDER_COLLISION_DYNAMIC_FRICTION_RATIO = 1.0
    COLLIDER_COLLISION_STATIC_FRICTION_RATIO = 1.0
