"""MC2 solver 自有标识。"""

MC2_SOLVER_ID = "mc2"
MC2_SLOT_KIND = "mc2"

MC2_SETUP_MESH_CLOTH = "mesh_cloth"
MC2_SETUP_BONE_CLOTH = "bone_cloth"
MC2_SETUP_BONE_SPRING = "bone_spring"
MC2_SETUP_TYPES = (
    MC2_SETUP_MESH_CLOTH,
    MC2_SETUP_BONE_CLOTH,
    MC2_SETUP_BONE_SPRING,
)

MC2_STATS_CHANNEL = "mc2_stats"
MC2_DEBUG_DRAW_MODE = "mc2"
MC2_INTERACTION_RESOURCE_KEY = "mc2_interaction_v0"
MC2_FUSED_PRODUCT_SLOT_KIND = "mc2_fused_cpu_product_v1"
