"""MC2 solver 自有标识。"""

MC2_SOLVER_ID = "mc2"
MC2_SLOT_KIND = "mc2"

MC2_SETUP_MESH_CLOTH = "mesh_cloth"
MC2_SETUP_BONE_CLOTH = "bone_cloth"
MC2_SETUP_BONE_SPRING = "bone_spring"
MC2_SETUP_TYPES = (
    MC2_SETUP_MESH_CLOTH,
    MC2_SETUP_BONE_CLOTH,
    MC2_SETUP_BONE_SPRING,
)

MC2_BACKEND_AUTO = "auto"
MC2_BACKEND_PYTHON = "python"
MC2_BACKEND_CPP = "cpp"
MC2_BACKENDS = (MC2_BACKEND_AUTO, MC2_BACKEND_PYTHON, MC2_BACKEND_CPP)

MC2_MESH_RESULT_CHANNEL = "mc2_mesh_delta"
MC2_BONE_RESULT_CHANNEL = "mc2_bone_transform"
MC2_STATS_CHANNEL = "mc2_stats"
MC2_DEBUG_DRAW_MODE = "mc2"
