"""跨工具共用的逐键形态键事实。"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ShapeKeyStandardInfo:
    """一个标准的 UI 信息和默认属性。"""

    identifier: str
    family: str
    label: str
    description: str
    categories: frozenset = frozenset()
    source_urls: tuple = ()
    side_reliable: bool = False


@dataclass(frozen=True)
class ShapeKeySpec:
    """某个标准中的一个原始形态键记录。"""

    standard: str
    family: str
    name: str
    role: str = 'TEMPLATE'
    region: str = 'OTHER'
    side: str = 'NONE'
    semantic: str = 'OTHER'
    canonical: str | None = None
    context: str | None = None
    side_reliable: bool = False
    tags: frozenset = frozenset()
    source_urls: tuple = ()
    note: str = ''

    @property
    def is_template(self):
        return self.role == 'TEMPLATE'

STANDARD_INFOS = (
    ShapeKeyStandardInfo(
        identifier='ARKIT',
        family='ARKIT',
        label='ARKit',
        description='ARKit 形态键列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=('https://arkit-face-blendshapes.com/',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='VRCHAT',
        family='VRCHAT',
        label='VRChat',
        description='VRChat 形态键列表',
        categories=frozenset(['AVATAR', 'LIP_SYNC']),
        source_urls=(),
        side_reliable=False,
    ),
    ShapeKeyStandardInfo(
        identifier='MMD',
        family='MMD',
        label='MMD',
        description='MMD 形态键列表',
        categories=frozenset(['AVATAR', 'MMD']),
        source_urls=(),
        side_reliable=False,
    ),
    ShapeKeyStandardInfo(
        identifier='VRM',
        family='VRM',
        label='VRM 0.x',
        description='VRM 0.x 形态键列表',
        categories=frozenset(['AVATAR', 'VRM']),
        source_urls=(),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='VRM1',
        family='VRM1',
        label='VRM 1.0',
        description='VRM 1.0 表情预设列表',
        categories=frozenset(['AVATAR', 'VRM']),
        source_urls=('https://vrm.dev/vrm1/expression/',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='QUEST_PRO',
        family='META',
        label='Meta Movement',
        description='Meta Movement 形态键列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=('https://developers.meta.com/horizon/documentation/unity/move-face-tracking/',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='META_VISEME',
        family='META_VISEME',
        label='Meta Viseme',
        description='Meta Movement 15 音素列表',
        categories=frozenset(['LIP_SYNC']),
        source_urls=('https://developers.meta.com/horizon/documentation/unity/move-face-tracking/',),
        side_reliable=False,
    ),
    ShapeKeyStandardInfo(
        identifier='PICO',
        family='PICO',
        label='PICO',
        description='PICO 52 形态键和 20 音素列表',
        categories=frozenset(['FACE_TRACKING', 'LIP_SYNC']),
        source_urls=('https://developer-cn.picoxr.com/document/unity/face-tracking/',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='OCULUS_VISEME',
        family='OCULUS_VISEME',
        label='Oculus Viseme',
        description='Oculus/Meta 15 音素列表',
        categories=frozenset(['LIP_SYNC']),
        source_urls=('https://developers.meta.com/horizon/documentation/unity/audio-ovrlipsync-viseme-reference/',),
        side_reliable=False,
    ),
    ShapeKeyStandardInfo(
        identifier='VIVE_SRANIPAL',
        family='VIVE_SRANIPAL',
        label='VIVE SRanipal',
        description='VIVE SRanipal 眼部和唇部列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=(
            'https://docs.vrcft.io/docs/tutorial-avatars/'
            'tutorial-avatars-extras/compatibility/vive-sranipal',
        ),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='VIVE_OPENXR',
        family='VIVE_OPENXR',
        label='VIVE OpenXR',
        description='XR_HTC_facial_tracking 表情列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=('https://hub.vive.com/apidoc/api/VIVE.OpenXR.FacialTracking.html',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='UNIFIED_EXPRESSIONS_BASE',
        family='UNIFIED_BASE',
        label='Unified-base',
        description='Unified 基础形态键列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=('https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/unified-blendshapes',),
        side_reliable=True,
    ),
    ShapeKeyStandardInfo(
        identifier='UNIFIED_EXPRESSIONS_BLEND',
        family='UNIFIED_BLEND',
        label='Unified-blend',
        description='Unified 混合形态键列表',
        categories=frozenset(['FACE_TRACKING']),
        source_urls=('https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/unified-blendshapes',),
        side_reliable=False,
    ),
)
_STANDARD_BY_ID = {
    info.identifier: info
    for info in STANDARD_INFOS
}


def _key(
        standard, name, *, role='TEMPLATE', region='OTHER',
        side='NONE', semantic='OTHER', canonical=None, context=None,
        tags=(), note=''):
    """只补标准级公共字段，不根据名称推断任何事实。"""
    info = _STANDARD_BY_ID[standard]
    return ShapeKeySpec(
        standard=standard,
        family=info.family,
        name=name,
        role=role,
        region=region,
        side=side,
        semantic=semantic,
        canonical=canonical,
        context=context,
        side_reliable=info.side_reliable,
        tags=info.categories | frozenset(tags),
        source_urls=info.source_urls,
        note=note,
    )


SHAPE_KEY_SPECS = (
    # ARKit
    _key('ARKIT', 'browInnerUp'),
    _key('ARKIT', 'browDownLeft'),
    _key('ARKIT', 'browDownRight'),
    _key('ARKIT', 'browOuterUpLeft'),
    _key('ARKIT', 'browOuterUpRight'),
    _key(
        'ARKIT', 'eyeLookUpLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
    ),
    _key(
        'ARKIT', 'eyeLookUpRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
    ),
    _key(
        'ARKIT', 'eyeLookDownLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
    ),
    _key(
        'ARKIT', 'eyeLookDownRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
    ),
    _key(
        'ARKIT', 'eyeLookInLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.left',
    ),
    _key(
        'ARKIT', 'eyeLookInRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.right',
    ),
    _key(
        'ARKIT', 'eyeLookOutLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.left',
    ),
    _key(
        'ARKIT', 'eyeLookOutRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.right',
    ),
    _key(
        'ARKIT', 'eyeBlinkLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'ARKIT', 'eyeBlinkRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'ARKIT', 'eyeSquintLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
    ),
    _key(
        'ARKIT', 'eyeSquintRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
    ),
    _key(
        'ARKIT', 'eyeWideLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
    ),
    _key(
        'ARKIT', 'eyeWideRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
    ),
    _key('ARKIT', 'cheekPuff'),
    _key('ARKIT', 'cheekSquintLeft', region='EYE', side='LEFT', semantic='EYE_ORBIT'),
    _key('ARKIT', 'cheekSquintRight', region='EYE', side='RIGHT', semantic='EYE_ORBIT'),
    _key('ARKIT', 'noseSneerLeft'),
    _key('ARKIT', 'noseSneerRight'),
    _key('ARKIT', 'jawOpen', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'jawForward', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'jawLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'jawRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthFunnel', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthPucker', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthRollUpper', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthRollLower', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthShrugUpper', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthShrugLower', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthClose', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthSmileLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthSmileRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthFrownLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthFrownRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthDimpleLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthDimpleRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthUpperUpLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthUpperUpRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthLowerDownLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthLowerDownRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthPressLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthPressRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthStretchLeft', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'mouthStretchRight', region='MOUTH', semantic='MOUTH'),
    _key('ARKIT', 'tongueOut', region='MOUTH', semantic='MOUTH'),

    # VRChat
    _key('VRCHAT', 'vrc.v_aa', region='MOUTH', semantic='VISEME', canonical='viseme.aa'),
    _key('VRCHAT', 'vrc.v_ih', region='MOUTH', semantic='VISEME', canonical='viseme.ih'),
    _key('VRCHAT', 'vrc.v_ou', region='MOUTH', semantic='VISEME', canonical='viseme.ou'),
    _key('VRCHAT', 'vrc.v_e', region='MOUTH', semantic='VISEME', canonical='viseme.e'),
    _key('VRCHAT', 'vrc.v_oh', region='MOUTH', semantic='VISEME', canonical='viseme.oh'),
    _key('VRCHAT', 'vrc.v_sil', region='MOUTH', semantic='VISEME', canonical='viseme.sil'),
    _key('VRCHAT', 'vrc.v_pp', region='MOUTH', semantic='VISEME', canonical='viseme.pp'),
    _key('VRCHAT', 'vrc.v_ff', region='MOUTH', semantic='VISEME', canonical='viseme.ff'),
    _key('VRCHAT', 'vrc.v_th', region='MOUTH', semantic='VISEME', canonical='viseme.th'),
    _key('VRCHAT', 'vrc.v_dd', region='MOUTH', semantic='VISEME', canonical='viseme.dd'),
    _key('VRCHAT', 'vrc.v_kk', region='MOUTH', semantic='VISEME', canonical='viseme.kk'),
    _key('VRCHAT', 'vrc.v_ch', region='MOUTH', semantic='VISEME', canonical='viseme.ch'),
    _key('VRCHAT', 'vrc.v_ss', region='MOUTH', semantic='VISEME', canonical='viseme.ss'),
    _key('VRCHAT', 'vrc.v_nn', region='MOUTH', semantic='VISEME', canonical='viseme.nn'),
    _key('VRCHAT', 'vrc.v_rr', region='MOUTH', semantic='VISEME', canonical='viseme.rr'),
    _key(
        'VRCHAT', 'vrc.looking_up',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_up.both',
    ),
    _key(
        'VRCHAT', 'vrc.looking_down',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_down.both',
    ),
    _key(
        'VRCHAT', 'vrc.blink',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
    ),
    _key(
        'VRCHAT', 'vrc.blink (3.0)',
        role='ALIAS',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
    ),

    # MMD
    _key(
        'MMD', 'まばたき',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
    ),
    _key('MMD', '笑い', region='EYE', side='BOTH', semantic='EYELID'),
    _key(
        'MMD', 'ウィンク',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'MMD', 'ウィンク右',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'MMD', 'ウィンク２',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'MMD', 'ｳｨﾝｸ２右',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key('MMD', 'なごみ', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'はぅ', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'びっくり', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'じと目', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'ｷﾘｯ', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'はちゅ目', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', '星目'),
    _key('MMD', 'はぁと'),
    _key('MMD', '瞳小'),
    _key('MMD', '瞳縦潰れ'),
    _key('MMD', '光下'),
    _key('MMD', '恐ろしい子！', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'ハイライト消'),
    _key('MMD', '映り込み消'),
    _key('MMD', '喜び', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'わぉ?!'),
    _key('MMD', 'なごみω'),
    _key('MMD', '悲しむ', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', '敵意'),
    _key('MMD', 'あ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'い', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'う', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'え', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'お', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'あ２', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'ん', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '▲', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '∧', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '□', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'ワ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'ω', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'ω□', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'にやり', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'にやり２', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'にっこり', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'ぺろっ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'てへぺろ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'てへぺろ２', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口角上げ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口角下げ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口横広げ', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '歯無し上', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '歯無し下', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '真面目'),
    _key('MMD', '困る'),
    _key('MMD', 'にこり'),
    _key('MMD', '怒り'),
    _key('MMD', '上'),
    _key('MMD', '下'),
    _key('MMD', 'ジト目', role='ALIAS', region='EYE', side='BOTH', semantic='EYELID'),
    _key('MMD', 'えー', role='ALIAS', region='MOUTH', semantic='MOUTH'),
    _key('MMD', 'はんっ！', role='ALIAS', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口横狭め', role='ALIAS', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口上', role='ALIAS', region='MOUTH', semantic='MOUTH'),
    _key('MMD', '口下', role='ALIAS', region='MOUTH', semantic='MOUTH'),

    # VRM 0.x
    _key(
        'VRM', 'A',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.a',
        context='VRM0_VISEME',
    ),
    _key(
        'VRM', 'I',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.i',
        context='VRM0_VISEME',
    ),
    _key(
        'VRM', 'U',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.u',
        context='VRM0_VISEME',
    ),
    _key(
        'VRM', 'E',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.e',
        context='VRM0_VISEME',
    ),
    _key(
        'VRM', 'O',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.o',
        context='VRM0_VISEME',
    ),
    _key(
        'VRM', 'Blink',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
        tags=('VRM0_MARKER',),
    ),
    _key('VRM', 'Joy', tags=('VRM0_MARKER',)),
    _key('VRM', 'Angry', tags=('VRM0_MARKER',)),
    _key('VRM', 'Sorrow', tags=('VRM0_MARKER',)),
    _key('VRM', 'Fun', tags=('VRM0_MARKER',)),
    _key(
        'VRM', 'LookUp',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_up.both',
        tags=('VRM0_MARKER',),
    ),
    _key(
        'VRM', 'LookDown',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_down.both',
        tags=('VRM0_MARKER',),
    ),
    _key(
        'VRM', 'LookLeft',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_left.both',
        tags=('VRM0_MARKER',),
    ),
    _key(
        'VRM', 'LookRight',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_right.both',
        tags=('VRM0_MARKER',),
    ),
    _key(
        'VRM', 'Blink_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
        tags=('VRM0_MARKER',),
    ),
    _key(
        'VRM', 'Blink_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
        tags=('VRM0_MARKER',),
    ),

    # VRM 1.0
    _key('VRM1', 'Neutral'),
    _key('VRM1', 'Happy'),
    _key('VRM1', 'Angry'),
    _key('VRM1', 'Sad'),
    _key('VRM1', 'Relaxed'),
    _key('VRM1', 'Surprised'),
    _key('VRM1', 'Aa', region='MOUTH', semantic='VISEME', canonical='viseme.aa'),
    _key('VRM1', 'Ih', region='MOUTH', semantic='VISEME', canonical='viseme.ih'),
    _key('VRM1', 'Ou', region='MOUTH', semantic='VISEME', canonical='viseme.ou'),
    _key('VRM1', 'Ee', region='MOUTH', semantic='VISEME', canonical='viseme.ee'),
    _key('VRM1', 'Oh', region='MOUTH', semantic='VISEME', canonical='viseme.oh'),
    _key(
        'VRM1', 'Blink',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
    ),
    _key(
        'VRM1', 'BlinkLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'VRM1', 'BlinkRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'VRM1', 'LookUp',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_up.both',
    ),
    _key(
        'VRM1', 'LookDown',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_down.both',
    ),
    _key(
        'VRM1', 'LookLeft',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_left.both',
    ),
    _key(
        'VRM1', 'LookRight',
        region='EYE',
        side='BOTH',
        semantic='EYE_GAZE',
        canonical='eye.look_right.both',
    ),

    # Meta Movement
    _key(
        'QUEST_PRO', 'EYES_LOOK_UP_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_DOWN_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_LEFT_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_left.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_RIGHT_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_right.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_UP_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_DOWN_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_LEFT_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_left.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_LOOK_RIGHT_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_right.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_CLOSED_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'EYES_CLOSED_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LID_TIGHTENER_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LID_TIGHTENER_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'UPPER_LID_RAISER_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'UPPER_LID_RAISER_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
        tags=('META_LONG',),
    ),
    _key('QUEST_PRO', 'BROW_LOWERER_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'BROW_LOWERER_L', tags=('META_LONG',)),
    _key('QUEST_PRO', 'INNER_BROW_RAISER_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'INNER_BROW_RAISER_L', tags=('META_LONG',)),
    _key('QUEST_PRO', 'OUTER_BROW_RAISER_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'OUTER_BROW_RAISER_L', tags=('META_LONG',)),
    _key('QUEST_PRO', 'NOSE_WRINKLER_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'NOSE_WRINKLER_L', tags=('META_LONG',)),
    _key(
        'QUEST_PRO', 'CHEEK_RAISER_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_ORBIT',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'CHEEK_RAISER_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_ORBIT',
        tags=('META_LONG',),
    ),
    _key('QUEST_PRO', 'CHEEK_PUFF_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'CHEEK_PUFF_L', tags=('META_LONG',)),
    _key('QUEST_PRO', 'CHEEK_SUCK_R', tags=('META_LONG',)),
    _key('QUEST_PRO', 'CHEEK_SUCK_L', tags=('META_LONG',)),
    _key('QUEST_PRO', 'JAW_DROP', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIPS_TOWARD', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key(
        'QUEST_PRO', 'JAW_SIDEWAYS_RIGHT',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'JAW_SIDEWAYS_LEFT',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key('QUEST_PRO', 'JAW_THRUST', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_SUCK_RT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_SUCK_LT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_SUCK_RB', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_SUCK_LB', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_FUNNELER_RT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_FUNNELER_LT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_FUNNELER_RB', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_FUNNELER_LB', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_PUCKER_R', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_PUCKER_L', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key(
        'QUEST_PRO', 'UPPER_LIP_RAISER_R',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'UPPER_LIP_RAISER_L',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LOWER_LIP_DEPRESSOR_R',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LOWER_LIP_DEPRESSOR_L',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LIP_CORNER_PULLER_R',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LIP_CORNER_PULLER_L',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LIP_CORNER_DEPRESSOR_R',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'LIP_CORNER_DEPRESSOR_L',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key('QUEST_PRO', 'LIP_STRETCHER_R', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_STRETCHER_L', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'DIMPLER_R', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'DIMPLER_L', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'CHIN_RAISER_T', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'CHIN_RAISER_B', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_PRESSOR_R', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_PRESSOR_L', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_TIGHTENER_R', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'LIP_TIGHTENER_L', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'MOUTH_RIGHT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'MOUTH_LEFT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key(
        'QUEST_PRO', 'TONGUE_TIP_INTERDENTAL',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'TONGUE_TIP_ALVEOLAR',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'TONGUE_FRONT_DORSAL_PALATE',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'TONGUE_MID_DORSAL_PALATE',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key(
        'QUEST_PRO', 'TONGUE_BACK_DORSAL_VELAR',
        region='MOUTH',
        semantic='MOUTH',
        tags=('META_LONG',),
    ),
    _key('QUEST_PRO', 'TONGUE_OUT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),
    _key('QUEST_PRO', 'TONGUE_RETREAT', region='MOUTH', semantic='MOUTH', tags=('META_LONG',)),

    # Meta Viseme
    _key(
        'META_VISEME', 'SIL',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.sil',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'PP',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.pp',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'FF',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ff',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'TH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.th',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'DD',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.dd',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'KK',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.kk',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'CH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ch',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'SS',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ss',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'NN',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.nn',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'RR',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.rr',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'AA',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.aa',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'E',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.e',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'IH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ih',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'OH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.oh',
        context='META_VISEME',
    ),
    _key(
        'META_VISEME', 'OU',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ou',
        context='META_VISEME',
    ),

    # PICO
    _key(
        'PICO', 'EyeLookDown_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookDown_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookIn_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookIn_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookOut_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookOut_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookUp_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeLookUp_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeBlink_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeBlink_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeSquint_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeSquint_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeWide_L',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'EyeWide_R',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
        tags=('PICO_LONG',),
    ),
    _key('PICO', 'JawForward', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'JawLeft', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'JawOpen', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'JawRight', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthClose', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthFunnel', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthLeft', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthPucker', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthRight', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthRollLower', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthRollUpper', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthShrugLower', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthShrugUpper', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'TongueOut', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthDimple_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthDimple_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthFrown_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthFrown_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthLowerDown_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthLowerDown_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthPress_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthPress_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthSmile_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthSmile_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthStretch_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthStretch_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthUpperUp_L', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'MouthUpperUp_R', region='MOUTH', semantic='MOUTH', tags=('PICO_LONG',)),
    _key('PICO', 'BrowInnerUp', tags=('PICO_LONG',)),
    _key('PICO', 'CheekPuff', tags=('PICO_LONG',)),
    _key('PICO', 'BrowDown_L', tags=('PICO_LONG',)),
    _key('PICO', 'BrowDown_R', tags=('PICO_LONG',)),
    _key('PICO', 'BrowOuterUp_L', tags=('PICO_LONG',)),
    _key('PICO', 'BrowOuterUp_R', tags=('PICO_LONG',)),
    _key(
        'PICO', 'CheekSquint_L',
        region='EYE',
        side='LEFT',
        semantic='EYE_ORBIT',
        tags=('PICO_LONG',),
    ),
    _key(
        'PICO', 'CheekSquint_R',
        region='EYE',
        side='RIGHT',
        semantic='EYE_ORBIT',
        tags=('PICO_LONG',),
    ),
    _key('PICO', 'NoseSneer_L', tags=('PICO_LONG',)),
    _key('PICO', 'NoseSneer_R', tags=('PICO_LONG',)),
    _key(
        'PICO', 'PP',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.pp',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'CH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ch',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'o',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.o',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_O_PICO',
    ),
    _key(
        'PICO', 'O',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.ou',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_OU_PICO',
    ),
    _key(
        'PICO', 'I',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.i_back',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_I_BACK_PICO',
    ),
    _key(
        'PICO', 'u',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.u',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_U_PICO',
    ),
    _key(
        'PICO', 'RR',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.rr',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'XX',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.xx',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'aa',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.aa',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'i',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.i_front',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_I_FRONT_PICO',
    ),
    _key(
        'PICO', 'FF',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ff',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'U',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.uw',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_UW_PICO',
    ),
    _key(
        'PICO', 'TH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.th',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'kk',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.kk',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'SS',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ss',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'e',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.e',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_E_PICO',
    ),
    _key(
        'PICO', 'DD',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.dd',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'E',
        region='MOUTH',
        semantic='VISEME',
        canonical='pico.viseme.ei',
        context='PICO_VISEME',
        note='PICO 枚举：XR_VISEME_EI_PICO',
    ),
    _key(
        'PICO', 'nn',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.nn',
        context='PICO_VISEME',
    ),
    _key(
        'PICO', 'sil',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.sil',
        context='PICO_VISEME',
    ),

    # Oculus Viseme
    _key(
        'OCULUS_VISEME', 'viseme_sil',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.sil',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_PP',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.pp',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_FF',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ff',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_TH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.th',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_DD',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.dd',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_kk',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.kk',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_CH',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ch',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_SS',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.ss',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_nn',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.nn',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_RR',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.rr',
    ),
    _key(
        'OCULUS_VISEME', 'viseme_aa',
        region='MOUTH',
        semantic='VISEME',
        canonical='viseme.aa',
    ),
    _key('OCULUS_VISEME', 'viseme_E', region='MOUTH', semantic='VISEME', canonical='viseme.e'),
    _key('OCULUS_VISEME', 'viseme_I', region='MOUTH', semantic='VISEME', canonical='viseme.i'),
    _key('OCULUS_VISEME', 'viseme_O', region='MOUTH', semantic='VISEME', canonical='viseme.o'),
    _key('OCULUS_VISEME', 'viseme_U', region='MOUTH', semantic='VISEME', canonical='viseme.u'),

    # VIVE SRanipal
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Blink',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Wide',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Right',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_right.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Left',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_left.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Up',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Down',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Left_Squeeze',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Blink',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Wide',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Right',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_right.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Left',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_left.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Up',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Down',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
    ),
    _key(
        'VIVE_SRANIPAL', 'Eye_Right_Squeeze',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
    ),
    _key('VIVE_SRANIPAL', 'Eye_Frown', region='EYE', side='BOTH', semantic='EYE_ORBIT'),
    _key('VIVE_SRANIPAL', 'Jaw_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Jaw_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Jaw_Forward', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Jaw_Open', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Ape_Shape', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_Overturn', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_Overturn', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Pout', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Smile_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Smile_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Sad_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Sad_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Cheek_Puff_Right'),
    _key('VIVE_SRANIPAL', 'Cheek_Puff_Left'),
    _key('VIVE_SRANIPAL', 'Cheek_Suck'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_UpRight', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_UpLeft', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_DownRight', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_DownLeft', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Upper_Inside', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_Inside', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Mouth_Lower_Overlay', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_LongStep1', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_LongStep2', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_Down', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_Up', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_Right', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_Left', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_Roll', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_UpLeft_Morph', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_UpRight_Morph', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_DownLeft_Morph', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_SRANIPAL', 'Tongue_DownRight_Morph', region='MOUTH', semantic='MOUTH'),

    # VIVE OpenXR
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_BLINK_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_DOWN_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_IN_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_OUT_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_SQUEEZE_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_UP_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_LEFT_WIDE_HTC',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_BLINK_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_DOWN_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_IN_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_OUT_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_SQUEEZE_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_UP_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
    ),
    _key(
        'VIVE_OPENXR', 'XR_EYE_EXPRESSION_RIGHT_WIDE_HTC',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
    ),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_CHEEK_PUFF_LEFT_HTC'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_CHEEK_PUFF_RIGHT_HTC'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_CHEEK_SUCK_HTC'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_JAW_FORWARD_HTC', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_JAW_LEFT_HTC', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_JAW_OPEN_HTC', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_JAW_RIGHT_HTC', region='MOUTH', semantic='MOUTH'),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_APE_SHAPE_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNLEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNRIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_INSIDE_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_LEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_OVERLAY_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_OVERTURN_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_LOWER_RIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_POUT_HTC', region='MOUTH', semantic='MOUTH'),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_RAISER_LEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_RAISER_RIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_STRETCHER_LEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_STRETCHER_RIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_INSIDE_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_LEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_OVERTURN_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_RIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_UPLEFT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_MOUTH_UPPER_UPRIGHT_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_DOWNLEFT_MORPH_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_DOWNRIGHT_MORPH_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_DOWN_HTC', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_LEFT_HTC', region='MOUTH', semantic='MOUTH'),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_LONGSTEP1_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_LONGSTEP2_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_RIGHT_HTC', region='MOUTH', semantic='MOUTH'),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_ROLL_HTC', region='MOUTH', semantic='MOUTH'),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_UPLEFT_MORPH_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key(
        'VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_UPRIGHT_MORPH_HTC',
        region='MOUTH',
        semantic='MOUTH',
    ),
    _key('VIVE_OPENXR', 'XR_LIP_EXPRESSION_TONGUE_UP_HTC', region='MOUTH', semantic='MOUTH'),

    # Unified-base
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookOutRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookInRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookUpRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookDownRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookOutLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_out.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookInLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_in.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookUpLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_up.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeLookDownLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_GAZE',
        canonical='eye.look_down.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeClosedRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.closed.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeClosedLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.closed.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeSquintRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.squint.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeSquintLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.squint.left',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeWideRight',
        region='EYE',
        side='RIGHT',
        semantic='EYELID',
        canonical='eye.wide.right',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'EyeWideLeft',
        region='EYE',
        side='LEFT',
        semantic='EYELID',
        canonical='eye.wide.left',
    ),
    _key('UNIFIED_EXPRESSIONS_BASE', 'EyeDilationRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'EyeDilationLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'EyeConstrictRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'EyeConstrictLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowPinchRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowPinchLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowLowererRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowLowererLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowInnerUpRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowInnerUpLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowOuterUpRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'BrowOuterUpLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NoseSneerRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NoseSneerLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NasalDilationRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NasalDilationLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NasalConstrictRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NasalConstrictLeft'),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'CheekSquintRight',
        region='EYE',
        side='RIGHT',
        semantic='EYE_ORBIT',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BASE', 'CheekSquintLeft',
        region='EYE',
        side='LEFT',
        semantic='EYE_ORBIT',
    ),
    _key('UNIFIED_EXPRESSIONS_BASE', 'CheekPuffRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'CheekPuffLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'CheekSuckRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'CheekSuckLeft'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawOpen', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthClosed', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawForward', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawBackward', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawClench', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'JawMandibleRaise', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckUpperRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckUpperLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckLowerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckLowerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckCornerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipSuckCornerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipFunnelUpperRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipFunnelUpperLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipFunnelLowerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipFunnelLowerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipPuckerUpperRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipPuckerUpperLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipPuckerLowerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'LipPuckerLowerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperUpRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperUpLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthLowerDownRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthLowerDownLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperDeepenRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperDeepenLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthUpperLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthLowerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthLowerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthCornerPullRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthCornerPullLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthCornerSlantRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthCornerSlantLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthFrownRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthFrownLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthStretchRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthStretchLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthDimpleRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthDimpleLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthRaiserUpper', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthRaiserLower', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthPressRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthPressLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthTightenerRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'MouthTightenerLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueOut', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueUp', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueDown', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueRoll', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueBendDown', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueCurlUp', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueSquish', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueFlat', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueTwistRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'TongueTwistLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'SoftPalateClose', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'ThroatSwallow'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NeckFlexRight'),
    _key('UNIFIED_EXPRESSIONS_BASE', 'NeckFlexLeft'),

    # Unified-blend
    _key(
        'UNIFIED_EXPRESSIONS_BLEND', 'EyeClosed',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.closed.both',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BLEND', 'EyeWide',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.wide.both',
    ),
    _key(
        'UNIFIED_EXPRESSIONS_BLEND', 'EyeSquint',
        region='EYE',
        side='BOTH',
        semantic='EYELID',
        canonical='eye.squint.both',
    ),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'EyeDilation'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'EyeConstrict'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowDownRight'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowDownLeft'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowDown'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowInnerUp'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowUpRight'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowUpLeft'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'BrowUp'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'NoseSneer'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'NasalDilation'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'NasalConstrict'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'CheekPuff'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'CheekSuck'),
    _key(
        'UNIFIED_EXPRESSIONS_BLEND', 'CheekSquint',
        region='EYE',
        side='BOTH',
        semantic='EYE_ORBIT',
    ),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipSuckUpper', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipSuckLower', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipSuck', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipFunnelUpper', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipFunnelLower', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipFunnel', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipPuckerUpper', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipPuckerLower', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'LipPucker', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthUpperUp', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthLowerDown', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthOpen', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSmileRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSmileLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSmile', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSadRight', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSadLeft', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthSad', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthStretch', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthDimple', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthTightener', region='MOUTH', semantic='MOUTH'),
    _key('UNIFIED_EXPRESSIONS_BLEND', 'MouthPress', region='MOUTH', semantic='MOUTH'),
)


def _validate_data():
    standard_ids = {info.identifier for info in STANDARD_INFOS}
    seen = set()
    for spec in SHAPE_KEY_SPECS:
        if spec.standard not in standard_ids:
            raise RuntimeError(f"未知形态键标准：{spec.standard}")
        identity = (spec.standard, spec.name)
        if identity in seen:
            raise RuntimeError(
                f"标准 {spec.standard} 中存在重复形态键：{spec.name}")
        seen.add(identity)


_validate_data()


__all__ = (
    'ShapeKeySpec',
    'ShapeKeyStandardInfo',
    'SHAPE_KEY_SPECS',
    'STANDARD_INFOS',
)
